### ISSUE TITLE
Improving documentation on exception handling

### ISSUE THREAD

**Issue by jasalt** [phel-lang/phel-lang.org#87]
I found a possibly broken example code [control flow documentation](https://github.com/phel-lang/phel-lang.org/blob/master/content/documentation/control-flow.md#try-catch-and-finally) with throwing exceptions, if I did not miss something while learning these parts.

Throwables don't seem to be available without `use` statement, leading to `Can not resolve type Exception` error when trying to instantiate them with `(php/new Exception "ID is not integer")` for throwing.

In REPL, `(use \Exception)` is required beforehand, or eg. with the cli-skeleton project `main.phel` the following addition:

```
(ns cli-skeleton\main
  (:require cli-skeleton\modules\adder-module :refer [adder])
  (:use \Exception))
```

**Comment by jasalt** [comment]
On second note, I saw old issue https://github.com/phel-lang/phel-lang.org/issues/73 about this part of docs being hard to find. I also had this experience initially having to look around for a while to find out that exceptions are actually supported, although the location under control flow is quite logical.

Symbols `try`, `catch` and `throw` are missing from the [API listing](https://phel-lang.org/documentation/api/) page, and thus don't show up in the Docs search at all. Full text search might help some in similar situations.. at least Google search for "phel exceptions" finds there, hehe.

**Comment by Chemaclass** [comment]
Can you submit a PR @jasalt with your fixed line `  (:use \Exception))`?
I will work on adding the missing symbols try, catch and throw to the API listing, thank for reporting :)

**Comment by smeghead** [comment]
@jasalt 
Thank you.

Alternatively, you can refer to the full path namespace `\Exception` directly.

``
(try
  (throw (php/new \Exception))
  (catch \Exception e “error”))
```
As an example code, it may be simpler.

**Comment by jasalt** [comment]
@smeghead a-ha indeed, thank's. I sent that in PR for now as it works in both REPL or when running as a script. Clojure works bit differently there, so it is slightly confusing still what ends up available for default or not, but at least the code example should work with that to get started with.

**Comment by jasalt** [comment]
Looking how exceptions work otherwise, I find that the throwable type seems to be turned into `Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException` in REPL session, while only the message from original exception is shown (thankfully at least).

I have mostly experimented with this on REPL so not sure how it works during script evaluation.

Example output in default cli-skeleton project (PHP 8.2.20 / Debian):

```
user@mx-p14s ~/dev/phel-test/cli-skeleton ‹main●›
$ vendor/bin/phel repl

phel:1> (throw (php/new \TypeError))
Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException:
in /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14 (gen: /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14)

#0 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/RequireEvaluator.php(42): Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException::fromThrowable()
#1 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(111): Phel\Compiler\Domain\Evaluator\RequireEvaluator->eval()
#2 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(70): Phel\Compiler\Application\EvalCompiler->evalNode()
#3 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/CompilerFacade.php(57): Phel\Compiler\Application\EvalCompiler->evalString()
#4 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/RunFacade.php(79): Phel\Compiler\CompilerFacade->eval()
#5 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(208): Phel\Run\RunFacade->eval()
#6 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(142): Phel\Run\Infrastructure\Command\ReplCommand->analyzeInputBuffer()
#7 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(99): Phel\Run\Infrastructure\Command\ReplCommand->loopReadLineAndAnalyze()
#8 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Command/Command.php(279): Phel\Run\Infrastructure\Command\ReplCommand->execute()
#9 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run()
#10 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#11 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#12 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php(24): Symfony\Component\Console\Application->run()
#13 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/bin/phel(45): Phel\Console\Infrastructure\ConsoleBootstrap->run()
#14 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/bin/phel(46): {closure}()
#15 /home/user/dev/phel-test/cli-skeleton/vendor/bin/phel(120): include('/home/user/dev/...')

phel:2> (throw (php/new \TypeError "It is a TypeError BTW!"))
Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException: It is a TypeError BTW!
in /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14 (gen: /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14)

#0 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/RequireEvaluator.php(42): Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException::fromThrowable()
#1 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(111): Phel\Compiler\Domain\Evaluator\RequireEvaluator->eval()
#2 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(70): Phel\Compiler\Application\EvalCompiler->evalNode()
#3 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/CompilerFacade.php(57): Phel\Compiler\Application\EvalCompiler->evalString()
#4 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/RunFacade.php(79): Phel\Compiler\CompilerFacade->eval()
#5 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(208): Phel\Run\RunFacade->eval()
#6 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(142): Phel\Run\Infrastructure\Command\ReplCommand->analyzeInputBuffer()
#7 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(99): Phel\Run\Infrastructure\Command\ReplCommand->loopReadLineAndAnalyze()
#8 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Command/Command.php(279): Phel\Run\Infrastructure\Command\ReplCommand->execute()
#9 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run()
#10 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#11 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#12 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php(24): Symfony\Component\Console\Application->run()
#13 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/bin/phel(45): Phel\Console\Infrastructure\ConsoleBootstrap->run()
#14 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/bin/phel(46): {closure}()
#15 /home/user/dev/phel-test/cli-skeleton/vendor/bin/phel(120): include('/home/user/dev/...')
```
Not sure if this is expected behavior, bug or what, but managing by cramming enough information into the message.

**Comment by Chemaclass** [comment]
@jasalt The documentation is now fixed https://github.com/phel-lang/phel-lang/pull/764 - it will be released soon in a patch version. Regarding the exception type converted to `CompiledCodeIsMalformedException` seems to be another topic. Do you mind opening another issue to keep track of it and discuss that topic in another thread so we can close this one? Thank you!

**Comment by Chemaclass** [comment]
New release 0.15.3 with improved documentation already deployed https://phel-lang.org/documentation/api/
